arrowParens = 'always'
bracketSameLine = false
bracketSpacing = true
embeddedLanguageFormatting = 'auto'
endOfLine = 'lf'
htmlWhitespaceSensitivity = 'css'
insertPragma = false
jsxSingleQuote = false
plugins = ["prettier-plugin-astro"]
printWidth = 100
proseWrap = 'preserve'
quoteProps = 'as-needed'
rangeStart = 0
requirePragma = false
semi = true
singleQuote = true
tabWidth = 2
trailingComma = 'all'
useTabs = false

[[overrides]]
files = '*.astro'
options = {parser = 'astro'}
